version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    container_name: backend-docker
    restart: always
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@cluster0.mongodb.net/database-name?retryWrites=true&w=majority
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend-docker
    restart: always
    environment:
      - REACT_APP_API_URL=https://your-api-url.com
